package dev.jayvijaygohil.nbateamsviewer

import com.google.gson.Gson
import dev.jayvijaygohil.nbateamsviewer.model.Team

fun getSuccessDummyResponse(): List<Team> = Gson().fromJson(SUCCESS_DUMMY_RESPONSE_JSON, ArrayList<Team>()::class.java).toList()

const val SUCCESS_DUMMY_RESPONSE_JSON = "[\n" +
        "   {\n" +
        "      \"wins\":45,\n" +
        "      \"losses\":20,\n" +
        "      \"full_name\":\"Boston Celtics\",\n" +
        "      \"id\":1,\n" +
        "      \"players\":[\n" +
        "         {\n" +
        "            \"id\":37729,\n" +
        "            \"first_name\":\"Kadeem\",\n" +
        "            \"last_name\":\"Allen\",\n" +
        "            \"position\":\"SG\",\n" +
        "            \"number\":45\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":30508,\n" +
        "            \"first_name\":\"Aron\",\n" +
        "            \"last_name\":\"Baynes\",\n" +
        "            \"position\":\"C\",\n" +
        "            \"number\":46\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":30847,\n" +
        "            \"first_name\":\"Jabari\",\n" +
        "            \"last_name\":\"Bird\",\n" +
        "            \"position\":\"SG\",\n" +
        "            \"number\":26\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":45455,\n" +
        "            \"first_name\":\"Jaylen\",\n" +
        "            \"last_name\":\"Brown\",\n" +
        "            \"position\":\"G-F\",\n" +
        "            \"number\":7\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":989,\n" +
        "            \"first_name\":\"Gordon\",\n" +
        "            \"last_name\":\"Hayward\",\n" +
        "            \"position\":\"G-F\",\n" +
        "            \"number\":20\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":12,\n" +
        "            \"first_name\":\"Al\",\n" +
        "            \"last_name\":\"Horford\",\n" +
        "            \"position\":\"F-C\",\n" +
        "            \"number\":42\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":6154,\n" +
        "            \"first_name\":\"Kyrie\",\n" +
        "            \"last_name\":\"Irving\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":11\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":12714,\n" +
        "            \"first_name\":\"Shane\",\n" +
        "            \"last_name\":\"Larkin\",\n" +
        "            \"position\":\"PG\",\n" +
        "            \"number\":8\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":1965,\n" +
        "            \"first_name\":\"Greg\",\n" +
        "            \"last_name\":\"Monroe\",\n" +
        "            \"position\":\"F-C\",\n" +
        "            \"number\":55\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":2444,\n" +
        "            \"first_name\":\"Marcus\",\n" +
        "            \"last_name\":\"Morris\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":13\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":12275,\n" +
        "            \"first_name\":\"Abdel\",\n" +
        "            \"last_name\":\"Nader\",\n" +
        "            \"position\":\"PF\",\n" +
        "            \"number\":28\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":31438,\n" +
        "            \"first_name\":\"Semi\",\n" +
        "            \"last_name\":\"Ojeleye\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":37\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":31126,\n" +
        "            \"first_name\":\"Terry\",\n" +
        "            \"last_name\":\"Rozier\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":12\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":24740,\n" +
        "            \"first_name\":\"Marcus\",\n" +
        "            \"last_name\":\"Smart\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":36\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":52651,\n" +
        "            \"first_name\":\"Jayson\",\n" +
        "            \"last_name\":\"Tatum\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":0\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":60058,\n" +
        "            \"first_name\":\"Daniel\",\n" +
        "            \"last_name\":\"Theis\",\n" +
        "            \"position\":\"F-C\",\n" +
        "            \"number\":27\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":52283,\n" +
        "            \"first_name\":\"Guerschon\",\n" +
        "            \"last_name\":\"Yabusele\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":30\n" +
        "         }\n" +
        "      ]\n" +
        "   },\n" +
        "   {\n" +
        "      \"wins\":20,\n" +
        "      \"losses\":44,\n" +
        "      \"full_name\":\"Brooklyn Nets\",\n" +
        "      \"id\":2,\n" +
        "      \"players\":[\n" +
        "         {\n" +
        "            \"id\":802,\n" +
        "            \"first_name\":\"Quincy\",\n" +
        "            \"last_name\":\"Acy\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":13\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":53393,\n" +
        "            \"first_name\":\"Jarrett\",\n" +
        "            \"last_name\":\"Allen\",\n" +
        "            \"position\":\"F-C\",\n" +
        "            \"number\":31\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":233,\n" +
        "            \"first_name\":\"DeMarre\",\n" +
        "            \"last_name\":\"Carroll\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":9\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":5912,\n" +
        "            \"first_name\":\"Allen\",\n" +
        "            \"last_name\":\"Crabbe\",\n" +
        "            \"position\":\"G-F\",\n" +
        "            \"number\":33\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":415,\n" +
        "            \"first_name\":\"Dante\",\n" +
        "            \"last_name\":\"Cunningham\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":44\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":11989,\n" +
        "            \"first_name\":\"Spencer\",\n" +
        "            \"last_name\":\"Dinwiddie\",\n" +
        "            \"position\":\"PG\",\n" +
        "            \"number\":8\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":24692,\n" +
        "            \"first_name\":\"Milton\",\n" +
        "            \"last_name\":\"Doyle\",\n" +
        "            \"position\":\"PG\",\n" +
        "            \"number\":14\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":5967,\n" +
        "            \"first_name\":\"Joe\",\n" +
        "            \"last_name\":\"Harris\",\n" +
        "            \"position\":\"G-F\",\n" +
        "            \"number\":12\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":30838,\n" +
        "            \"first_name\":\"Rondae\",\n" +
        "            \"last_name\":\"Hollis-Jefferson\",\n" +
        "            \"position\":\"F\",\n" +
        "            \"number\":24\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":24860,\n" +
        "            \"first_name\":\"Caris\",\n" +
        "            \"last_name\":\"LeVert\",\n" +
        "            \"position\":\"SF\",\n" +
        "            \"number\":22\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":2109,\n" +
        "            \"first_name\":\"Jeremy\",\n" +
        "            \"last_name\":\"Lin\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":7\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":6330,\n" +
        "            \"first_name\":\"Timofey\",\n" +
        "            \"last_name\":\"Mozgov\",\n" +
        "            \"position\":\"C\",\n" +
        "            \"number\":20\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":37621,\n" +
        "            \"first_name\":\"Jahlil\",\n" +
        "            \"last_name\":\"Okafor\",\n" +
        "            \"position\":\"C\",\n" +
        "            \"number\":4\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":37752,\n" +
        "            \"first_name\":\"D'Angelo\",\n" +
        "            \"last_name\":\"Russell\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":1\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":24863,\n" +
        "            \"first_name\":\"Nik\",\n" +
        "            \"last_name\":\"Stauskas\",\n" +
        "            \"position\":\"G-F\",\n" +
        "            \"number\":2\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":32213,\n" +
        "            \"first_name\":\"James\",\n" +
        "            \"last_name\":\"Webb III\",\n" +
        "            \"position\":\"SF\",\n" +
        "            \"number\":0\n" +
        "         },\n" +
        "         {\n" +
        "            \"id\":37705,\n" +
        "            \"first_name\":\"Isaiah\",\n" +
        "            \"last_name\":\"Whitehead\",\n" +
        "            \"position\":\"G\",\n" +
        "            \"number\":15\n" +
        "         }\n" +
        "      ]\n" +
        "   }\n" +
        "]"